kind: Deployment
apiVersion: apps/v1
metadata:
  name: angular-15-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-15-client
  template:
    metadata:
      labels:
        app: angular-15-client
    spec:
      containers:
        - name: angular-15-client
          image: quay.io/redhat-user-workloads/atul-fulambarkar-tenant/tutorialsonline-ng/angular-15-client-tutorialsonline:build-37984-1691759337
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: angular-15-client-svc
spec:
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: angular-15-client
